bookfebproject/bookapp/urls.py
from django.urls import path

from bookapp import views
app_name = 'bookapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register',views.register,name='register'),
    path('detail/<int:BookId>',views.detail,name='detail'),
    path('trend',views.trending,name='trending'),
    path('discount',views.MegaDiscount,name='MegaDiscount'),
    path('book',views.getBooks,name='getbook'),
    path('category/<int:CategoryId>',views.booksByCategory,name='category'),
    path('author',views.authorList,name='author'),
    path('search',views.search,name='search'),
    path('booksByAuthor/<int:AuthorId>',views.booksByAuthor,name='booksByAuthor'),
    path('Message',views.MessageAddView,name='message'),
]

bookfebproject/bookproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookapp.urls')),
    path('cart',include('cartapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookfebproject/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('cartview', views.view_cart, name='cartview'),
    path('add_to_cart/<int:book_id>', views.add_to_cart, name='add_to_cart'),
    # path('unauthenticated/', views.unauthenticated_view, name='unauthenticated'),
]

bookfebproject/cartapp/models.py
from django.db import models
from bookapp.models import Book
from django.contrib.auth.models import User

# Create your models here.
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

bookfebproject/cartapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Book, CartItem
from django.contrib import messages

@login_required
def add_to_cart(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    action = request.POST.get('action')
    cart_item, created = CartItem.objects.get_or_create(user=request.user, book=book)
    
    if action == 'add':
        cart_item.quantity += 1
        cart_item.save()
        book.Stock -= 1
        book.save()
        messages.success(request, ' One Item added successfully.')
    elif action == 'remove':
        if cart_item.quantity > 0:
            cart_item.quantity -= 1
            cart_item.save()
            book.Stock += 1
            book.save()
            messages.success(request, 'Item removed from cart successfully.')
        if cart_item.quantity <= 0:
            cart_item.delete()
            messages.success(request, 'Item removed from cart successfully.')
        

    return redirect('cartapp:cartview')
   

def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = 0
    for item in cart_items:
        item.total_price = item.book.OfferPrice * item.quantity
        total_price += item.total_price
    return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price})

bookfebproject/cartapp/templates/cart.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Cart</title>
</head>
<body>
<h1 style="text-align: center;">My Cart</h1>
<hr>
{% if messages %}
    <div>
        {% for message in messages %}
            <div class="alert alert-success" role="alert" style="text-align: center;">{{ message }}</div>
        {% endfor %}
    </div>
    <meta http-equiv="refresh" content="1;url={% url 'cartapp:cartview' %}">
{% endif %}
    <div class="container">      
        <div class="row col-md-5" style="align-items: center;">
        {% for item in cart_items %}
        <div class="col-md-6">
            <img src="{{ item.book.BookCoverImage.url }}" alt="{{ item.book.BookCoverImageAlternativeText }}"
                style="width:180px;height:200px;">
        </div>
        <div class="col-md-5">
            <h6 style="display: inline;color:blueviolet;">{{ item.book.Title }}</h6>
            <h6>Offerprice:{{ item.book.OfferPrice }}</h6>
            <form action="{% url 'cartapp:add_to_cart' item.book.BookId %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="action" value="add">
                <a href="#" onclick="this.parentNode.submit();" style="text-decoration: none; color: inherit;">
                    <i class="fa-solid fa-square-plus" style="cursor: pointer;"></i>
                </a>
            </form>
    
            <span>Quantity:{{ item.quantity }}</span>
    
            <form action="{% url 'cartapp:add_to_cart' item.book.BookId %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="action" value="remove">
                <a href="#" onclick="this.parentNode.submit();" style="text-decoration: none; color: inherit;">
                    <i class="fa-solid fa-square-minus" style="cursor: pointer;"></i>
                </a>
                <h6>Total:{{ item.total_price }}</h6>    
                <h6>Stock:{{item.book.Stock}}</h6>
            </form>
            <hr>
        </div>   
        {% endfor %}
    </div>
    </div>

</body>
</html>
{% endblock %}

bookfebproject/cartapp/templates/unauthenticated.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthenticated</title>
</head>
<body>
    <h1>You are not authenticated</h1>
    <p>Please <a href="{% url 'bookapp:login' %}">login</a> to access this page.</p>
</body>
</html>