bookfebproject/bookapp/urls.py
from django.urls import path

from bookapp import views
app_name = 'bookapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register',views.register,name='register'),
    path('detail/<int:BookId>',views.detail,name='detail'),
    path('trend',views.trending,name='trending'),
    path('discount',views.MegaDiscount,name='MegaDiscount'),
    path('book',views.getBooks,name='getbook'),
    path('category/<int:CategoryId>',views.booksByCategory,name='category'),
    path('author',views.authorList,name='author'),
    path('search',views.search,name='search'),
    path('booksByAuthor/<int:AuthorId>',views.booksByAuthor,name='booksByAuthor'),
    path('Message',views.MessageAddView,name='message'),
]

bookfebproject/bookproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookapp.urls')),
    path('cart',include('cartapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookfebproject/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('cartview', views.view_cart, name='cartview'),
    path('add_to_cart/<int:book_id>', views.add_to_cart, name='add_to_cart'),
    # path('unauthenticated/', views.unauthenticated_view, name='unauthenticated'),
]

bookfebproject/bookapp/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Category(models.Model):
    CategoryId = models.AutoField(primary_key=True, editable=False)
    RefId = models.CharField(max_length=50, blank=True, null=True)
    CategoryName = models.CharField(max_length=300,blank=True, null=True)
    CategoryIcon = models.FileField(
        blank=True, null=True, upload_to='category/icon')
    CategoryImage = models.FileField(
        blank=True, null=True, upload_to='category/image')
    Description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.CategoryName
    
class Author(models.Model):
    AuthorId = models.AutoField(primary_key=True,editable=False)
    AuthorName = models.CharField(max_length=20,null=True,blank=True)
    AuthorImage = models.FileField(upload_to='author')
    Category = models.ForeignKey(Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.AuthorName
  
class Book(models.Model):
    BookId = models.AutoField(primary_key=True,editable=False)
    Title = models.CharField(max_length=30,blank=True,null=True)
    Description = models.TextField(blank=True, null=True)
    Authors = models.ForeignKey(Author,on_delete=models.CASCADE)
    BookCoverImage = models.FileField(
        blank=True, null=True, upload_to='book/cover')
    BookCoverImageAlternativeText=models.TextField(blank=True, null=True)
    
    Stock = models.IntegerField()
    UnitPrice = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    DiscountPercent = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    OfferPrice = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    
    Categories = models.ForeignKey(Category,on_delete=models.CASCADE)
    SubCategory = models.CharField(blank=True, null=True, max_length=50)
    SEOTitle = models.CharField(max_length=50,blank=True,null=True)
    SEOKeyword = models.CharField(max_length=50,blank=True,null=True)
    def __str__(self):
        return self.Title
    


class BookRating(models.Model):
    BookRatingId = models.AutoField(primary_key=True, editable=False)
    Books = models.ForeignKey(Book,on_delete=models.CASCADE)
    User = models.CharField(blank=True, null=True, max_length=50)
    Rating = models.IntegerField(default=0)
    Feedback = models.TextField(blank=True, null=True)
    RatingOn = models.DateTimeField(editable=False, default=datetime.now)
    
class Message(models.Model):
    SortId=models.DateTimeField(editable=False, default=datetime.now)
    MessageId = models.AutoField(primary_key=True, editable=False)
    Name=models.CharField(max_length=300,blank=False)
    EmailId=models.CharField(max_length=150,blank=False)
    Message=models.TextField(blank=False)
    Subject=models.TextField(null=True,blank=True)

bookfebproject/bookapp/forms.py
from django import forms
from . models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['Name','EmailId','Message','Subject']
        widgets = {
            'Name': forms.TextInput(attrs={'class': 'form-control'}),
            'EmailId': forms.EmailInput(attrs={'class': 'form-control'}),
            'Message': forms.Textarea(attrs={'class': 'form-control'}),
            'Subject': forms.TextInput(attrs={'class': 'form-control'}),
            
        }
        
        

bookfebproject/bookapp/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from . models import Book, Category, BookRating, Author
from django.db.models import Q
from django.contrib import auth
from django.contrib.auth.models import User
from . forms import MessageForm
# Create your views here.

def index(request):
    book = Book.objects.all()
    cat =Category.objects.all()
    return render(request,'index.html',{'book':book,'category':cat})

def getBooks(request):
    book = Book.objects.all()
    return render(request,'book.html',{'book':book})

def detail(request,BookId):
    books =  Book.objects.get(BookId=BookId)
    rating = BookRating.objects.filter(Books=books)
    return render(request,'detail.html',{'book':books,'rating':rating})

def login(request):
    if request.method == 'POST':
        username = request.POST['uname']
        password = request.POST['pwd']
        user= auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid credentials")
            return redirect('bookapp:login')
    return render(request,'login.html')

def register(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        address = request.POST['address']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        
        user = User.objects.create_user(first_name=firstname,last_name=lastname,
                                        username=username,email=email,
                                        password=password)
        user.save()
        print("user created")
        return redirect('bookapp:login')
    return render(request,'register.html')

def logout_view(request):
    auth.logout(request)
    return redirect('/')

def trending(request):
    trend = BookRating.objects.filter(Rating__gt=4)
    books = [rating.Books for rating in trend]  # Retrieve associated Book objects
    return render(request, 'trending.html', {'trending': trend, 'books': books})

def MegaDiscount(request):
    dis = Book.objects.filter(DiscountPercent__gt=35)
    return render(request, 'megaDiscount.html', {'discount': dis})

def MessageAddView(request):
    if request.method == 'POST':
        form = MessageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bookapp:index')
    else:
        form = MessageForm()
    return render(request, 'message.html', {'form': form})

def booksByCategory(request,CategoryId):
    cat = Category.objects.get(CategoryId=CategoryId)
    book = Book.objects.filter(Categories=cat)
    return render(request,"category.html",{'books':book,'category':cat})

def booksByAuthor(request,AuthorId):
    aut = Author.objects.get(AuthorId=AuthorId)
    books = Book.objects.filter(Authors=aut)
    context={
        'author':aut,
        'books':books
    }
    return render(request, 'authorBooks.html', context)


def authorList(request):
    author = Author.objects.all()
    return render(request,'author.html',{'author':author})

# def search(request):
#     if 'q' in request.GET:
#         print(request.GET)
#         query = request.GET['q']
#         # Perform case-insensitive search by concatenating multiple filters
#         books = Book.objects.filter(SEOKeyword__icontains=query) | Book.objects.filter(SEOTitle__icontains=query)
#         return render(request, 'searchResults.html', {'books': books, 'query': query})
#     else:
#         return render(request, 'searchResults.html', {})
def search(request):
    query = request.GET.get('q')
    books = None
    if query:
        q_object  = Q(SEOTitle__icontains=query)|Q(SEOKeyword__icontains=query)
        books = Book.objects.filter(q_object)
    return render(request, 'searchResults.html', {'books': books, 'query': query})

bookfebproject/bookapp/templates/author.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            {% for row in author %}
            <div class="col-sm-4">
                <div>
                    <img src="{{row.AuthorImage.url}}" alt="bokkalt" class="author-image" style="width:220px;height:250px;">
                </div>
                <div style="text-align: center;text-transform: uppercase;">{{row.AuthorName}}</div>
                <a class="btn btn-light" href="{% url 'bookapp:booksByAuthor' row.AuthorId %}" style="display:block;margin:0 auto;">View Books</a>
                <hr>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

bookfebproject/bookapp/templates/authorBooks.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if books %}
    <div style="text-align:center;font-weight:bolder;background-color: rgba(240, 240, 255, 0.609);
    padding:15px;border-radius:10px;">Showing books of {{author.AuthorName | upper}} </div>
    <div class="banner">
        <div class="container image-container">
            <div class="row">
                {% for row in books %}
                <div class="card">
                <div class="col-md-3">   
                    <a href="{% url 'bookapp:detail' row.BookId %}">
                        <img src="{{row.BookCoverImage.url}}" alt="{{row.BookCoverImageAlternativeText}}" 
                        style="width:240px;height:270px;">
                    </a>    
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    {% else %}
    <div style="text-align:center;font-weight:100;background-color: aliceblue;
    padding:10px;border-radius:8px;">Sorry!!!No books available 
    for {{author.AuthorName}}
    </div>
    {% endif %}
</body>
</html>
{% endblock %}

bookfebproject/bookapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book store Z</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'bookapp:index' %}"><b>BOOK STORE Z</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav">
        <div class="nav-item">
          <a class="nav-link" style="color: #007bff;font-weight: bold;" href="{% url 'bookapp:index' %}">Home</a>
        </div>
        <div class="nav-item">
          <a class="nav-link" style="color: #007bff;font-weight: bold;" href="{% url 'bookapp:trending' %}">Trending</a>
        </div>
        
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color: #007bff;font-weight: bold;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=2 %}">Comedy</a>
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=5 %}">Romance</a>
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=3 %}">Drama</a>
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=4 %}">Thriller</a>
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=6 %}">Fantasy</a>
            <a class="dropdown-item" href="{% url 'bookapp:category' CategoryId=1 %}">Horror</a>
          </div>
        </div>
        
        </div>
      <form class="d-flex ml-auto" action="{% url 'bookapp:search' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        
      </div>
    </div>
  </div>
</nav>
<br>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>

    {% block body %}
    {% endblock %}
    <!-- </div> -->
    
    {% include 'footer.html' %}
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

bookfebproject/bookapp/templates/book.html
{% extends 'base.html' %}
{% block body %}
<html>
    <head>
    </head>
    <body>
        <!-- <div class="banner-book"> -->
            <div class="card-container">
                <div class="row">
                    {% for row in book %}
                    <div class="col-md-3">
                        <div class="card" style="margin:0.5rem;">    
                            <a href="{% url 'bookapp:detail' row.BookId %}">
                            <img src="{{row.BookCoverImage.url}}" alt="{{row.BookCoverImageAlternativeText}}" style="width:330px;height:500px;">
                        </a> 
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        <!-- </div> -->
        
    </body>
</html>
{% endblock %}

bookfebproject/bookapp/templates/category.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<body>
    {% if books %}
    <div style="text-align:center;background-color: #f0f0f0; font-weight:bold;
    padding: 10px; border-radius: 5px;">Displaying {{category.CategoryName}} based books</div>
<div class="banner">  
<div class="container-fluid image-container">
    <div class="row">
            {% for row in books %}
                <div class="card mx-auto">
                    <a href="{% url 'bookapp:detail' row.BookId%}">
                    <img class="card-img-top" src="{{ row.BookCoverImage.url }}" alt="{{row.BookCoverImageAlternativeText}}"
                     style="width:230px;height:300px;"></a>
                </div>
            {% endfor %}        
    </div>
</div></div>
{% else %}
<div style="text-align: center;font-weight: bolder;background-color:#f0f0f0;
padding: 10px;border-radius: 5px;">No books available under this genre</div>
{% endif %}

</body>
</html>
{% endblock %} 

bookfebproject/bookapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="card-detail">
                            <img src="{{book.BookCoverImage.url}}" alt="{{book.BookCoverImageAlternativeText}}"
                             style="width:270px;height:250px;">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card text-center card-content-detail">
                            <p>Title: {{book.Title}}</p>
                            <p>Offer Price: <del>{{book.UnitPrice}}</del> {{book.OfferPrice}}</p>
                            <p>Author: {{book.Authors}}</p>
                            <p>Available No: {{book.Stock}}</p>
                            {% for row in rating %}
                            <p>Rating: {{row.Rating}}</p>
                            {% endfor %}
                        <a class="btn btn-primary mx-auto" style="width: 50%;" href="{% url 'cartapp:add_to_cart' book.BookId %}">Add to cart</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>

</html>
{% endblock %}

bookfebproject/bookapp/templates/footer.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous">

<footer>
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h3>About Us</h3>
          <p>Welcome to our book site! We aim to provide you with the latest and greatest in literature.</p>
        </div>
        <div class="col-md-4">
          <h3>Quick Links</h3>
          <ul>
            <li><a href="{% url 'bookapp:getbook' %}">Books</a></li>
            <li><a href="{% url 'bookapp:author' %}">Authors</a></li>
            <li><a href="{% url 'bookapp:message' %}">Quick quote</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h3>Follow Us</h3>
            <a href="#"><i class="fab fa-facebook"></i> Facebook</a><br>
            <a href="#"><i class="fab fa-twitter"></i> Twitter</a><br>
            <a href="#"><i class="fab fa-instagram"></i> Instagram</a>
        </div>
      </div>
    </div>
  </div>
    
  </footer>
  </html>

bookfebproject/bookapp/templates/index.html
{% extends 'base.html' %}
{% block body %}
<head>
</head>
<body>

  <div class="banner">
    <div class="banner-content">
      <h3 style="color:bisque;">Explore more with our store !!</h3>
      {% if user.is_authenticated %}
      <div style="color:bisque;">Welcome {{user.username}}</div>
      <a href="{% url 'bookapp:logout' %}" class="btn btn-info">Logout</a>
      {% else %}
      <a href="{% url 'bookapp:login' %}" class="btn btn-info">Login</a>
      <a href="{% url 'bookapp:register' %}" class="btn btn-info">Register</a>
      {% endif %}
    </div>
  </div>

  
<div class="container">
  <div class="row">
    {% for row in book|slice:":3" %}
    <div class="card ml-3">
        <img class="card-img-top" src="{{row.BookCoverImage.url}}" alt="{{book.BookCoverImageAlternativeText}}" 
        style="width:280px; height:310px; margin:1.5rem;cursor: pointer;">
        <div class="card-body">
          <h6 class="card-title">By {{row.Authors}}</h6>
          <a href="{% url 'bookapp:detail' row.BookId%}" class="btn btn-primary">More</a>
        </div>
    </div>  
    {% endfor %}      
  </div>
</div>
<br>

<div class="banner2">   
  <div class="banner-content2">
    <h3>Explore mega discount products with our store !!</h3>
    <a href="{% url 'bookapp:MegaDiscount' %}" class="btn btn-info">click here</a>
  </div>
</div>  

</body>
{% endblock %}

bookfebproject/bookapp/templates/login.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

</head>
<body>
    <div class="banner-1">
    <div class="login-container">
        <form method="POST" enctype="multipart/form-data" class="login-form">
            {% csrf_token %}
            <h2>Login</h2>
            <div class="input-group">
                <input type="text" name="uname" id="uname" placeholder="Enter Username" required>
            </div>
            <div class="input-group">
                <input type="password" name="pwd" id="pwd" placeholder="Enter Password" required>
            </div>
            <button type="submit" class="login-button">Login</button>
            <div>
            <span style="color:white;font-weight: bolder;">If new user!!! </span>
            <a href="{% url 'bookapp:register' %}" class="register-link">Register here</a>
            </div>
        </form> 
        <div style="text-align: center;font-weight: bold;color:aliceblue;">
            {% for msg in messages %}
            {{msg}}
            {% endfor %}
        </div>
         
    </div>       
</div>
{% endblock %}
</body>
</html>

bookfebproject/bookapp/templates/megaDiscount.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="text-align: center;padding:10px;
    background-color: aliceblue;font-weight: bold;">35% on or above discount products </div>
<div class="row">
    {% for row in discount %}
    <div class="col-md-3">
        <div class="card image-container">
            <a href="{% url 'bookapp:detail' row.BookId%}">
            <img class="card-img-top" src="{{ row.BookCoverImage.url }}" alt="{{row.BookCoverImageAlternativeText}}" style="width:325px;height:500px;">
            </a>
            <div class="card-body">
                <p class="card-text">OfferPrice: <del>{{row.UnitPrice}}</del>{{row.OfferPrice }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</body>
{% endblock %}
</html>

bookfebproject/bookapp/templates/message.html
{% extends 'base.html' %}
{% block body %}
<html>
    <head>
        <script>
            function showMessage(){
                alert("Thank you for your message!");
            }
        </script>
    </head>
</html>
    <div class=" banner-1">
        <div class="message-container">
            <form method="post" enctype="multipart/form-data" class="message-form" onsubmit="showMessage()">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>
            </div>
        </div>
        
    </div>
    {% endblock %} 

bookfebproject/bookapp/templates/register.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="banner">
        <div class="register-container">
            <form method="post" enctype="multipart/form-data" class="register-form">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" name="firstname" placeholder="enter firstname" required>
                </div>
                <div class="input-group">
                    <input type="text" name="lastname" placeholder="enter Last Name">
                </div>
                <div class="input-group">
                    <input type="text" name="address" placeholder="enter address">
                </div>
                <div class="input-group">
                    <input type="email" name="email" placeholder="enter email">
                </div>
                <div class="input-group">
                    <input type="text" name="username" placeholder="enter username" required>
                </div>
                <div class="input-group">
                    <input type="password" name="password" placeholder="enter password" required>
                </div>
                <div class="input-group">
                    <input type="password" name="cpassword" placeholder="confirm password" required>
                </div>
                
                    <button type="submit">Submit</button>
                    <span style="font-weight:bolder;color:black;">If already a registered user!!</span>
                    <a href="{% url 'bookapp:login' %}" class="login-link">Login</a>
            </form>
        </div>  
    </div>   
</body>
</html>
{% endblock %}

bookfebproject/bookapp/templates/searchResults.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
</head>
<body>

    {% if query %}
        <p>Your search for "{{ query }}" returned {{ books.count }} result(s).</p>
    {% else %}
        <p>No search query entered.</p>
    {% endif %}
<div class="container">
    <div class="row">
        {% if books %}
            {% for book in books %}
                <div class="card">
                        <a href="{% url 'bookapp:detail' book.BookId%}">
                            <img src="{{book.BookCoverImage.url}}" alt="{{book.BookCoverImageAlternativeText}}" style="width:300px;height:400px;">
                        </a>
                            <h6 style="font-weight: bold;">{{ book.Title }} by {{book.Authors | upper}}</h6>
                </div>
            {% endfor %}
        
    {% else %}
        <p>No results found.</p>
    {% endif %}
    </div>
    </div>
    
</body>
</html>
{% endblock %}

bookfebproject/bookapp/templates/trending.html
{% extends 'base.html' %}
{% block body %}
<html>
    <div style="text-align: center;padding:10px;
    background-color: aliceblue;font-weight: bold;">Top trending books</div>
<body>
<div class="banner">
    <div class="container-fluid image-container">
        <div class="row">
            {% for item2 in books %}
            <div class="card ml-3">    
                <div class="col-md-3">
                    <a href="{% url 'bookapp:detail' item2.BookId%}">
                    <img src="{{item2.BookCoverImage.url}}" alt="{{item2.BookCoverImageAlternativeText}}"
                     style="width:270x;height:330px;">
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

</body>
</html>
{% endblock %}